import type { Metadata } from "next";
import localFont from "next/font/local";
import "../app/globals.css";
import { ThemeProvider } from "@/theme/theme-provider";
import { Navbar } from "./components/navbar";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          enableSystem
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          themes={["light", "dark", "purple"]}
        >
          <Navbar />
          <main className="mt-16 ">
          {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
